- helm/charts/hydra/templates/_helpers.tpl
- helm/charts/hydra/templates/deployment.yaml
Fixes #29 
@aeneasr 
Introduced a helper function that does the comma separation. Patched the bad code.
Tested with 
```
helm install --values {path}.yaml --dry-run --debug > output.yaml
```
> Fix bug with --dangerous-allow-insecure-redirect-urls

- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
The current chart wasn't allowing to configure the deployment template's annotations, which becomes a problem in some setups. In order to allow to configure annotations such as Istio's `rewriteAppHTTPProbers` the chart for Hydra needs to provide a way to do so. 
We added a key to the `deployment` section with the name `annotations` and extended the template. The actual implementation is the same as it was already done for the Ingress templates.
> Make annotations for the hydra deployment configurable 

- yaml/oathkeeper/simple/oathkeeper-api.yaml
Updated the apiVersion to apps/v1 for the Deployment
Set the image to latest and added the selector field.
No GitHub issue but came across this issue while deploying Oathkeeper in Kubernetes.
In the latest version of Kubernetes (1.16) there was a breaking change which moved the Deployment kind out of beta. [https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)
I changed the apiVersion to apps/v1 instead of extensions/v1beta1. And to prevent another error also added a selector matchLabel.
Another change to make sure everything stays up to date is to change the image version to latest instead of version 0.13.
These changes allow this file to work again.
vulnerability, I confirm that I got green light (please contact …
> Update YAML k8 file for changes in Kubernetes 1.16

- docs/helm/hydra.md
The old version said oathkeeper in the configuration example. Changed this to say hydra
-
Change it to hydra to have a good example.
> Have hydra docs example say hydra instead of oath keeper

- .circleci/config.yml
- docs/helm/hydra.md
- helm/charts/example-idp/templates/service.yaml
- helm/charts/example-idp/values.yaml
- helm/charts/hive/templates/service-admin.yaml
- helm/charts/hive/templates/service-public.yaml
- helm/charts/hive/values.yaml
- helm/charts/hydra/templates/service-admin.yaml
- helm/charts/hydra/templates/service-public.yaml
- helm/charts/hydra/values.yaml
- helm/charts/oathkeeper/templates/service-api.yaml
- helm/charts/oathkeeper/templates/service-proxy.yaml
- helm/charts/oathkeeper/values.yaml
- yaml/oathkeeper/simple/oathkeeper-api.yaml
#57 
@aeneasr 
Allow for configurable annotations for the services to allow gateways (like Ambassador) to be configured through here instead of using CRDs.
> Configurable annotations for services

- helm/charts/hydra/charts/hydra-maester/templates/_helpers.tpl
To understand this change, one must know that the hydra chart doesn't include `hydra` in its resource name twice if it is already contained in the release name. This behaviour is defined in: `/helm/charts/hydra/templates/_helpers.tpl:14-22`
```
{{- define "hydra.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
```
A release name like `hydra-test`, `test-hydra` or simply `hydra` results in the admin service ingress name `<Release.Name>-admin`. A realese name without hydra results in …
> Fix hydra admin service name generator

- helm/charts/hydra/charts/hydra-maester/templates/rbac.yaml
Remove namespace as unsupported feature for roleRef.
This change must fix error installing hydra via helm3.
#96
> Remove namespace as unsupported feature

- helm/charts/hydra/Chart.yaml
- helm/charts/oathkeeper/Chart.yaml
- helm/charts/oathkeeper/charts/oathkeeper-master/Chart.yaml
Was setting up an instance and kept noticing the same typo while I was reviewing the charts. 
`deployoing` should be `deploying`
It's also in https://github.com/ory/k8s/blob/master/docs/helm/charts/index.yaml which I'm assuming is a autogenerated file, so I left it alone.
Fix spelling :-)
**Not applicable**
**Not applicable**
None
> fix: Correcting a trivial spelling mistake.

- docs/helm/hydra.md
- helm/charts/hydra/templates/_helpers.tpl
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/templates/secrets.yaml
- helm/charts/hydra/values.yaml
Signed-off-by: Clément BUCHART <clement@buchart.dev>
Simply allow using an existing secret to configure hydra.
Our use-case is as follow : 
We create a Google CloudSQL and a gcloud-sqlproxy via terraform while setting up our infrastructure.
We deploy Hydra as part of our application stack.
We would like to be able to have terraform create the secrets containing the DataSourceName as part of the infrastructure setup, and have hydra pick the secret up during the application deploy step.
> chore: Allow usage of existing secret in hydra chart

- helm/charts/hydra/values.yaml
make maester.adminService in hydra values.yaml a map to remove coalesce warning
https://github.com/ory/k8s/issues/134
maester.adminService is map with two values (name and port). Not having `{}` causes a warning.
```
maester:
enabled: true
adminService: {}  # -----> instead of adminService:
```
the changes.
> make maester.adminService in hydra values.yaml a map to remove warning

- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
Related to issue #136. We can discuss this issue on slack if you want.
Add a default value of `global.ory.oathkeeper.maester.name: maester` and edit the sidecar deployment's service account name to use to `{{ .Values.global.ory.oathkeeper.maester.name }}-account` 
the changes.
> fix: service account name for maester sidecar

- helm/charts/hydra-maester/templates/rbac.yaml
- helm/charts/oathkeeper-maester/templates/rbac.yaml
As of K8s 1.8, RBAC mode is stable and backed by the
rbac.authorization.k8s.io/v1 API
> upkeep: use GA RBAC resource api version

- docs/helm/kratos.md
Stale reference to Hydra in Kratos helm doc
> chore: Typo in configuration section

- helm/charts/kratos/Chart.yaml
- helm/charts/kratos/templates/_helpers.tpl
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/secrets.yaml
- helm/charts/kratos/values.yaml
The current chart is not working with kratos@v0.4.3
closes #154 
closes #151 
Replaced the usage of `secrets.session` with `secrets.cookie` as the key was renamed.
Maybe we should also respect `secrets.default` as they can be used as a fallback for `sessions.cookie`.
> fix: update kratos' helm chart to use secrets.cookie

- helm/charts/kratos/values.yaml
Current templates for admin and public ingresses expect `ingress.admin.hosts.*.paths` and `ingress.public.hosts*.paths` values to be of `list(string)` type, but default values contain objects with `path` and `backend` fields.
```yaml
{{- range .paths }}
- path: {{ . }}
backend:
serviceName: {{ $fullName }}-admin
servicePort: http
{{- end }}
```
It could make sense to change templates themselves, but service ports are already named and configured separately.
the changes.
> fix: Update kratos ingress default values

- helm/charts/oathkeeper-maester/values.yaml
> chore: update oathkeeper-maester version

- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
We are using hydra with a PostgreSQL database using TLS for remote connections.
In order to enforce security we want to use PostgreSQL `verify-full` or `verify-ca` sslmode which triggers server certificate validation against root CA
We need to mount the root CA certificate on the hydra pods to use this file in Postgres' DSN ( `sslrootcert` parameter)
Add helm values to authorize extra volumes to be mounted in hydra pods.
the changes.
> feat(hydra): extra volumes

- docs/helm/kratos.md
- helm/charts/kratos/templates/_helpers.tpl
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/secrets.yaml
- helm/charts/kratos/values.yaml
Secret management is often enough quite opinionated. To make it more flexible with different approaches, i's suggest to make it possible to switch-off the secret creation in kratos and be able inject ones own secret, no matter how that has been created.
the changes.
> feat: make secret-creation customizable in kratos

- helm/charts/kratos/templates/_helpers.tpl
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/secrets.yaml
- helm/charts/kratos/values.yaml
If `courier.smpt.connection_uri`  is set in values, it will be put into a secret in the same way how dsn or secrets are handled so far.
Implement same handling of value as for e.g. DSN. See #174.
the changes.
> feat: courier.smpt.connection_uri handled secret

- helm/charts/hydra-maester/Chart.yaml
- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
- helm/charts/hydra/Chart.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
The helm charts did not have the option to specify a priority class. In large Kubernetes clusters with some type of workloads, priorityClass gives more context to the scheduler about which pod to evict first.
[Official documentation](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/)
the changes.
Not sure about Helm chart versioning, on Helm stable that would have been a minor (feature addition) but I am not sure this is relevant here. I'll edit the PR if needed.
> feat: Add support for priorityClassName for Helm charts

- helm/charts/hydra/Chart.yaml
- helm/charts/hydra/templates/deployment.yaml
The Affinity option in the Hydra Chart is currently unavailable.
```
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template): unknown field "affinity" in io.k8s.api.core.v1.PodTemplateSpec
```
Move the affinity to the appropriate location in deployment.yaml.
the changes.
> fix: deployment.yaml of hydra chart

- docs/helm/kratos.md
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/values.yaml
Related to a discussion in Slack and loosely to this change: https://github.com/ory/x/commit/5b71f1e15fa3264e931d74e58965af73a51c8fc5
When setting up Kratos via Helm there are currently secrets in the config that should be passed in via another means.
The case I'm dealing with specifically is `kratos.config.selfservice.methods.oidc.config.providers`, which contains `client_id` and `client_secret` for each provider.
In this case my ideal scenario seems to be to set up secret containing the provider config, and then have that create env vars which Kratos can use to override config (in this case: `SELFSERVICE_METHODS_OIDC`.)
This requires that the secret is created separately, but I think that is beneficial. If it were up to Helm to create the secret then anyone who needed to run the chart …
> feat(kratos): Add support for specifying env vars from a secret

- .github/pull_request_template.md
- CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/8042a8da0b42c9ff50deb9860249f95c756af18f.
> chore: update repository template to 8042a8da

- helm/charts/hydra/Chart.yaml
- helm/charts/oathkeeper/Chart.yaml
#138 
@aeneasr this should be pretty easy to solve.
> Fix maester chart naming clashes between hydra & oathkeeper

- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
See #210  for details.
Change the template for deployments to pick up any values defined under `hydra.env` and render them in deployment.yaml as additional env entries. 
the changes.
works.
appropriate).
> feat(hydra): add support for custom env vars

- docs/helm/hydra.md
- helm/charts/hydra/Chart.yaml
- helm/charts/hydra/templates/_helpers.tpl
- helm/charts/hydra/templates/secrets.yaml
- helm/charts/hydra/values.yaml
#TBD
@k9ert
This PR allows the user of the chart to customize the Secrets' annotations so to better control the  object lifecycle in their Kubernetes cluster.
The use case I propose is a change of database host/cluster, which now would require getting around the chart or providing external secret or reinstalling the chart: with this change a user can allow the secret to be updated during helm upgrades with minimal distruption (such as deleting and reinstalling the chart) or external actions (such as manually modifying the secrets or providing one outside of the chart)
the …
> feat(hydra): make hydra chart secret annotations configurable

- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/values.yaml
https://github.com/ory/k8s/pull/211
This PR introduces extra environment variables and pre-defined datadog configuration for all charts.
the changes.
works.
appropriate).
This PR is similar to https://github.com/ory/k8s/pull/211 but applies to all charts and is standardized across all of them.
This PR introduces the mentioned features in the same way as https://github.com/ory/k8s/pull/209.
This PR has already been tested in our staging environment.
> feat(helm): add extra environment variables and datadog tracing to charts

- helm/charts/keto/.helmignore
- helm/charts/keto/Chart.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/NOTES.txt
- helm/charts/keto/templates/_helpers.tpl
- helm/charts/keto/templates/configmap.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/templates/hpa.yaml
- helm/charts/keto/templates/ingress.yaml
- helm/charts/keto/templates/secrets.yaml
- helm/charts/keto/templates/service.yaml
- helm/charts/keto/templates/serviceaccount.yaml
- helm/charts/keto/templates/tests/test-connection.yaml
- helm/charts/keto/values.yaml
https://github.com/ory/k8s/pull/89
This PR adds (finally) the last product of the Ory Corp to the list of Helm charts available.
the changes.
works.
appropriate).
This chart has been tested in a staging environment where oathkeeper and kratos have been set up and is working correctly.
This chart follows the latest template generated by Helm 3 and has a consistent structure with other charts available in this repository.
> feat(keto): add Keto Helm chart

- docs/helm/hydra-maester.md
- helm/charts/hydra-maester/Chart.yaml
- helm/charts/hydra-maester/templates/crd-job.yaml
- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
none
This PR allows the user of the chart to customize the labels of hydra-maester pod and job crd-init. This feature permit us to match global network policies which allow kubernetes api access, which is not available by default.
the changes.
works.
appropriate).
- CLA form respond with 404 error
- I didn't open an issue about this and don't find an existing. I choose to purpose feature insteed of issue.
- I use this chart on an "on premise" k8s cluster and hope merge it to community version.
> feat(hydra-maester): make hydra-maester pods labels customizable

- helm/charts/kratos/templates/configmap-templates.yaml
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/values.yaml
https://github.com/ory/k8s/issues/217
Currently it seems to be not possible to configure email templates in the Helm chart to customize the content of the emails kratos is sending for verification and recovery. It would be nice to have the possibility to configure this in values.yam.
the changes.
works.
appropriate).
> feat: Add possibility to configure email template overrides

- CONTRIBUTING.md
Updated repository templates to https://github.com/ory/meta/commit/bf0c44e61e70c3d0b783e95c898ebc3b0106f29d.
> chore: update repository template to bf0c44e6

- helm/charts/kratos/values.yaml
This PR fixes Kratos chart's `value.yaml` so it aligns with the actual manifest files. For example, in the `deployment.yaml`, it uses `.Values.resources` but in `value.yaml` it says the `resources` goes under the `deployment` key.
This PR also contains some minor comments change on the `value.yaml` aimed at reducing confusion. 
the changes.
works.
appropriate).
I do wonder if the `autoMigrate` should be true by default. I think this might fix most users interest.
> chore(kratos): fix kratos chart values.yaml to align with manifest files

- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/values.yaml
Implementation of the following discussion:
[https://github.com/ory/kratos/discussions/1111](https://github.com/ory/kratos/discussions/1111)
@tricky42 
The change is done because I needed to execute an init container so I could download cockroachdb credentials to connect to the database. The "extraInitContainers" is placed **before** the migration init container in the deployment template file so the migration can have the proper credentials to connect to the bd when executed. 
Maybe I should name the "extraInitContainers" "preExtraInitContainers"?
the changes.
works. …
> Added extraInitContainers to Kratos helm chart

- helm/charts/hydra/values.yaml
The values for hydra-maester aren't passed to the child chart. This fixes it.
> fix(hydra): fix values for maester in helm chart

- helm/charts/hydra/values.yaml
The indentation in the values files of hydra is not correct. Since the values can be specified from outside it's not really a problem.
However the indentation is not correct and this will lead to copy and paste errors. 
the changes.
works.
appropriate).
> fix: indentation for maester subchart in hydra chart

- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
None. The change is very simple.
Existing deployment.yaml doesn't have `lifecycle` hook. We want to add preStop hook to the deployment.yaml, so we add a new helm values `.Values.deployment.lifecycle` for this.
the changes.
works.
appropriate).
> feat: Add lifecycle values on deployment

- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
During one of our internal deployments which was related to a fix for the runtime issue, we had an instance that the Hydra deployment was taking more time connecting to the database than usual. Unfortunately that meant it took more than preconfigured probe checks in Hydra's chart failing our deployment.
This PR allows for configuring custom probe timeouts by adding new values to the chart. The existing values are preserved as default values.
the changes.
works.
appropriate).
> feat: Allow configuring probes values

- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/templates/secrets.yaml
- helm/charts/oathkeeper/values.yaml
This PR makes secret management optional for the helm chart.  This allows external management of the JWKS secret data (including rotation, etc).
#120 
When `secret.manage: false`, the helm chart will not manage the secret.  This allows external management of the JWKS secret data (including rotation, etc).
the changes.
works.
appropriate).
> feat: make secret management optional

- helm/charts/hydra-maester/crds/crd-oauth2clients.yaml
- helm/charts/oathkeeper-maester/crds/crd-rules.yaml
- Followup to: https://github.com/ory/hydra-maester/pull/68
- Followup to: https://github.com/ory/oathkeeper-maester/pull/48
- Fixes: https://github.com/ory/oathkeeper-maester/issues/49
Update CRDs in charts to be in line with the current controllers
the changes.
works.
appropriate).
> fix: Update CRDs after API changes

- helm/charts/kratos/Chart.yaml
- helm/charts/kratos/templates/deployment.yaml
Despite this variable is stated in values file, deployment for kratos doesn't use it.
Add extraEnv to Deployment file
the changes.
works.
appropriate).
> fix(kratos): respect value of deployment.extraEnv

- helm/charts/hydra/templates/deployment.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/values.yaml
Similar to #252, during deployment we noticed that the readiness check of the Kratos service took longer than the default `timeoutSeconds` parameter. However, there is no option to adapt this parameter. 
This PR allows for configuring custom probe timeouts by adding new values to the chart for Kratos and Keto, similarly as #252 did for Hydra.
the changes.
works.
appropriate).
> feat: allow configuring probe values for kratos & keto

- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/templates/rbac.yaml
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper-maester/templates/rbac.yaml
- Fixes https://github.com/ory/k8s/issues/138
Use `fullname` instead of name in templates to allow multiple installations.
the changes.
works.
appropriate).
Recommend way of installing multiple releases:
```bash
helm install oathkeeper-maester ./helm/charts/oathkeeper-maester --namespace foo1
helm install oathkeeper-maester-2 ./helm/charts/oathkeeper-maester --namespace foo2
```
> fix: use fullname instead of name

- helm/charts/keto/templates/job-migration.yaml
Extended keto helm chart to support extra volumes and mounts in migration job.
If DSN is referencing to a file with a certificate this certificate needs to be mounted, currently, you can do it only if you mount the certificate in the CM that is already defined in the chart. This will not be suitable in most cases as certificates usually are stored in separate resources like secrets. I have added the same way of extra mounting volumes as it's done in the keto deployment.
the changes.
works.
appropriate).
@Demonsthere please take a look
FYI @aeneasr
> feat: support extra volumes and mounts in migration job

- helm/charts/oathkeeper-maester/templates/rbac.yaml
#276 updated resource names to use `fullname`, but this role binding was overlooked.
The result is that the Maester service does not have the needed permissions to list Rule resources:
```
E0706 00:58:21.003914       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.2/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Rule: failed to list *v1alpha1.Rule: rules.oathkeeper.ory.sh is forbidden: User "system:serviceaccount:default:test-oathkeeper-maester-account" cannot list resource "rules" in API group "oathkeeper.ory.sh" at the cluster scope
``` 
- [X ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [ X] I have read the [security policy](../security/policy).
- [ X] I confirm that this pull request does not address a security …
> fix: use the correct ServiceAccount name in the ClusterRoleBinding

- .circleci/values/hydra.yaml
- helm/charts/hydra/templates/_helpers.tpl
- helm/charts/hydra/templates/ingress-admin.yaml
- helm/charts/hydra/templates/ingress-public.yaml
- helm/charts/hydra/values.yaml
- Fixes https://github.com/ory/hydra/issues/2609
the changes.
works.
appropriate).
> feat: improve parsing of secret envs

- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/values.yaml
Taken the two values and deployment templates from Kratos, and implemented them in Oathkeeper.
the changes.
works.
appropriate).
This allows a user to easily mount TLS certificates into the Oathkeeper deployment to allow the pod to terminate TLS.
> feat: adding extraVolumeMounts & extraVolumes to Oathkeeper Chart

- helm/charts/hydra/templates/job-migration.yaml
Inject `imagePullSecrets` values into hydra automigrate job when registry authentication is needed to pull the image
Bug Fix: 
`imagePullSecrets` are not inject into hydra automigrate job, preventing hydra to be instanciated when authentication to the image registry is needed.
the changes.
works.
appropriate).
> fix: Inject imagePullSecrets in hydra migrate job

- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/templates/job-migration.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/templates/job-migration.yaml
- helm/charts/kratos-selfservice-ui-node/templates/deployment.yaml
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
Allows setting `securityContext.enabled: false` which omits the securityContext-setting for the containers. In some environment (e.g. OpenShift) you don't want to set them (e.g. they are set automatically).
https://github.com/ory/k8s/issues/421
the changes.
works.
appropriate).
> feat: Allow disabling securityContext

- .circleci/values/hydra.yaml
- .circleci/values/keto.yaml
- .circleci/values/kratos.yaml
- .circleci/values/oathkeeper.yaml
- .circleci/values/prometheus.yaml
- Makefile
- helm/charts/hydra/templates/service-admin.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/servicemonitor-metrics.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/templates/service-admin.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/templates/service-metrics.yaml
- helm/charts/oathkeeper/values.yaml
- added Prometheus stack to the CI kind cluster [#428](https://github.com/ory/k8s/issues/428)
- added ServiceMonitor for hydra, the same way it was done for kratos
- make ServiceMonitors configurable for hydra, kratos, keto and oathkeeper
the changes.
works.
appropriate).
> feat: add servicemonitor for hydra & make servicemonitors configurable

- helm/charts/hydra/templates/_helpers.tpl
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/_helpers.tpl
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/templates/_helpers.tpl
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/templates/_helpers.tpl
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/values.yaml
Introduces two new boolean values `secret.hashSumEnabled` and `configMap.hashSumEnabled`, both true by default, which will auto create/managed checksum annotations on `spec.template.metadata.annotations` for relevant pod resources. This will automatically mark those pods to be recreated after the changes.
https://github.com/ory/k8s/issues/413
the changes.
works.
appropriate).
I did a deep-dive into this while creating this PR, and I noticed an issue. The secrets in a few charts have auto-generated secret values by …
> feat: add support for checksum annotations

- helm/charts/kratos/templates/deployment.yaml
the changes.
works.
appropriate).
> fix: deployment template smtp secret ref

- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
This is a fix to apply the nodeSelector that is applied to kratos deployment to courier statefulSet
the changes.
works.
appropriate).
> fix: nodeSelector not applied to kratos courier

- helm/charts/keto/templates/ingress-read.yaml
- helm/charts/keto/templates/ingress-write.yaml
Keto ingress always return 503,  because it map service wrong (should be `keto-read:grpc-read`, `keto-write:grpc-write` instead of  `keto:grpc-read`  `keto:grpc-write` )
> fix: keto ingress wrong service name

- helm/charts/hydra/templates/deployment.yaml
This fixes duplicated volumeMounts in the hydra migrate init container which causes the install to fail when
```
automigration:
enabled: true
type: initContainer
```
> fix(hydra): removes duplicated volumeMounts yaml int automigrate init container

- hacks/values/hydra.yaml
- hacks/values/keto.yaml
- hacks/values/kratos.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/templates/job-migration.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/templates/job-migration.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/values.yaml
**Note**: Replaces #419, which appears to be inactive/stale. 
Allow the ability to pass through custom commands & args into the migration container. 
For our use case, we run the GCP cloud-sql-proxy sidecar containers, the migrations fail to run as they sometimes start before the proxy has started. This change allows us to add a `sleep` (or a `wait-for-it` script) to the migration command so that it waits for the sql proxy to be available. 
> feat: allow custom commands and args on migration containers

- docs/helm/hydra.md
- helm/charts/hydra-maester/templates/rbac.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/templates/job-migration.yaml
1. Hydra: to not pass DSN environment variable, when `.Values.hydra.config.dsn` isn't specified. https://github.com/ory/k8s/pull/416
2. Hydra Maester: to not create ClusterRole, when `singleNamespaceMode` is enabled, add relevant permission to Role.
3. Hydra Maester: remove `.Release.Namespace` suffixes for Roles/RoleBindings as they are already per namespace (to unify naming).
DSN change.
When `.Values.hydra.config.dsn` isn't specified - DSN environment variable is passed into the pod with empty value, as it is read from secret, dns key (it is created in any case, with or without value). My …
> chore: hydra DSN is empty, maester in singleNamespaceMode with Role

- helm/charts/kratos/templates/NOTES.txt
After installing kratos with helm, the notes say:
```
export KRATOS_PUBLIC_URL=http://127.0.0.1:80/
export KRATOS_ADMIN_URL=http://127.0.0.1:80/
```
The kratos cli cannot handle the last `/` (at least version v0.10.1, v0.10.0 and v0.9.0-alpha.3):
```
kratos ls identities 100 1
2022/09/27 08:57:43 [DEBUG] GET http://127.0.0.1:8081//admin/identities?page=100&per_page=1
```
(See `//`)
Just with:
```
export KRATOS_PUBLIC_URL=http://127.0.0.1:80
export KRATOS_ADMIN_URL=http://127.0.0.1:80
```
it works as expected. So I opened this PR to avoid the same issue for others.
Would be happy about a merge =)
> chore: removed / from helm notes because kratos cli cannot handle the /

- docs/helm/hydra.md
This PR updates the hydra helm chart install documentation.
It adds a misplaced part about k8s secrets, updates the `autoMigrate` config option to `automigration` and introduces some other minor changes.
none
Following the tutorial with a postgre database deployed in the same cluster:
```
microk8s helm3 install hydra -n test \
--set 'hydra.config.dsn=postgres://operator:<pwd>@<postgre-ip>:5432/postgres' \
--set 'hydra.config.urls.self.issuer=http://localhost:4444' \
--set 'hydra.config.urls.login=http://localhost:3000/login' \
--set 'hydra.config.urls.consent=http://localhost:3000/consent' \
--set …
```
> docs: update hydra readme

- docs/helm/kratos.md
This PR updates the kratos helm chart install documentation. The doc is updated with a complete `kratos-config.yaml` where users could install kratos without errors. I also updated the section on setting identity schemas, providing up to date options. I removed the `--set-file` option from identity schema section as I can't reproduce it. 
#449 
> docs: update kratos doc

- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/values.yaml
- Fixes https://github.com/ory/k8s/issues/503
> chore: remove deprecated datadog options

- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
Expose the `--endpoint` argument of `hydra-maester` so a fresh install of `hydra-maester` works correctly with Hydra 2.x.
**BREAKING CHANGES:** This patch changes `adminService.endpoint` to `/admin/clients` to be
compatible with `Hydra 2.x`. To keep the existing behavior (for `Hydra 1.x`) please set
`adminService.endpoint` to `/clients`.
New Issue: The `hydra-maester` chart does not expose the `--endpoint` argument which needs to be set to `/admin/clients` for Hydra 2.x.
Hydra does perform a `307` redirect but this includes the `localhost` portion which cause the following error. This error was a bit confusing to me at first becuase I thought I had just misconfigured maester but after pulling a local copy of maester and running `dlv` I could see that it's just [following `307` in …
> fix: expose --endpoint argument in chart for Hydra 2.x support

- helm/charts/example-idp/templates/NOTES.txt
There is a bug in the NOTES.txt that corrupts shown address. 
To reproduce this bug you need to install/upgrade release with values
```
ingress:
enabled: true
```
Previously notes used the whole path structure instead of the path itself.  It was leading to an incorrect path shown after helm install/upgrade. 
The path before changes: 
```
1. Get the application URL by running these commands:
https://example-idp.int.chainstack.commap[path:/ pathType:ImplementationSpecific]
```
The path after changes:
```
1. Get the application URL by running these commands:
https://example-idp.int.chainstack.com/
```
> fix: notes for example-idp in ingress mode

- helm/charts/kratos/README.md
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/templates/statefulset-svc.yaml
- helm/charts/kratos/values.yaml
To enable self-service for multiple schemas, you must run multiple Kratos instances with different default schema. There is no such configuration available currently in the Kratos Helm Chart. It could be accomplished by running multiple releases of the chart - but it will result in spawning multiple couriers - leading to multiplying emails send.
This PR is simply adding option to disable courier, allowing to enable it only for one release of Kratos.
> feat: add config to disable courier

- hacks/values/kratos.yaml
- helm/charts/kratos/templates/configmap-templates.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
Currently in the Kratos chart, we cannot use the `emailTemplates` config to set recovery/verification code templates because `_` isn't allowed in configmap name. 
This PR fixes this by allowing user to use `verification-code` or `recovery-code` key to set these templates. 
N/A
> fix: support recovery_code and verification_code email templates

- helm/charts/hydra/templates/hpa.yaml
- helm/charts/keto/templates/hpa.yaml
- helm/charts/kratos/templates/hpa-v2.yaml
- helm/charts/oathkeeper/templates/hpa-controller.yaml
Since Hydra and Kratos are using v2beta2 HPA API version, and Keto and Oathkeeper use v2beta1, we have some inconsistency across the charts.
This patch fix that and bring all modules to the latest version defined.
> fix: consistent hpa api version

- docs/helm/oathkeeper.md
Fixes a dangling sentence by adding a link to the Oathkeeper configuration.
Also removes a reference to a non-existent table.
> docs: fix reference to oathkeeper configuration

- helm/charts/hydra-maester/crds/crd-oauth2clients.yaml
- helm/charts/hydra-maester/values.yaml
Upgrade hydra-maester to v0.0.27 which adds Ready condition to OAuth2ClientStatus. This allows k8s clients with support for status conditions to determine if the client has been synchronized with hydra and the corresponding secret for an OAuth2Client is ready to be read.
hydra-maester PR: https://github.com/ory/hydra-maester/pull/122
This change fixes an issue I was having when trying to use hydra-maester with OAuth2Clients in terraform. Since this is a custom resource I was using the kubernetes_manifest resource, and I was also using terraform to extract the client credentials from the k8s secret. However, this was not working because terraform attempts to read the secret immediately after it finishes creating the OAuth2Client, and when the secret doesn't exist yet (which happens like …
> fix: upgrade hydra-maester chart to support OAuth2Client 'Ready' condition

- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/job-migration.yaml
This is only a bugfix.
Where job.extraEnv is specified it should be used in preference to deployment.extraEnv, which was not happening.
If deployment.extraEnv had been specified before it would have always been used. Previously the chart wouldn't render at all with job.extraEnv specified, but deployment.extraEnv not specified.
Tested by specifying job.extraEnv and seeing in the output of `helm template .`
> fix: make migration extraEnv work through job.extraEnv

- helm/charts/hydra-maester/Chart.yaml
- helm/charts/hydra-maester/crds/crd-oauth2clients.yaml
- helm/charts/hydra-maester/values.yaml
Update Hydra Maestro oauth2clients CR spec to add the skip consent field for the client.
https://github.com/ory/docs/pull/1437
https://github.com/ory/hydra-maester/pull/124
> feat: add hydra client skip consent

- helm/charts/hydra/README.md
- helm/charts/hydra/templates/janitor-cron-job.yaml
- helm/charts/hydra/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/cleanup-cron-job.yaml
- helm/charts/kratos/values.yaml
In order for the cronjobs to send traces about their execution, they require as environment variables the correct host.
But we cannot pass them today.
> feat: extra env variables for Hydra & Kratos cronjobs

- helm/charts/hydra-maester/crds/crd-oauth2clients.yaml
Update Hydra Maestro oauth2clients CR spec to add the jwks uri field for the client.
Waiting https://github.com/ory/hydra-maester/pull/126 to be merged.
> feat: add hydra client jwks uri

- hacks/values/hydra-maester.yaml
- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
This pull request adds the ability to configure hydra-maester to point to a hydra admin endpoint that has TLS enabled. Previous to this PR, "http" was hard-coded in the admin host, causing HTTP 400 responses when talking to a hydra admin endpoint with TLS enabled. Furthermore, this PR adds the ability to add volume/volumeMounts to the deployment to add CA certs. 
This simply adds in a few missing command line options from hydra-maester.
> feat: added configuration for TLS enabled hydra admin services

- hacks/values/hydra.yaml
- hacks/values/keto.yaml
- hacks/values/kratos.yaml
- hacks/values/oathkeeper-maester.yaml
- hacks/values/oathkeeper.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper-maester/values.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/values.yaml
At the moment, only the hydra and hydra-maester charts allow configuring the priorityClassName. This pull request introduces this configuration option to the other charts as well.
> feat: added priorityClassName to all charts

- helm/charts/oathkeeper-maester/README.md
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper-maester/values.yaml
Allow adding deployment level labels to Oathkeeper Maester, Copy of what Hydra Maester has
> feat: extra labels

- docs/helm/kratos.md
This is just a minor doc "fix", as it turns out, you can't use "-" in helm. And I took the example to literal. Hope that's alright.
> chore: update helm set-file example

- hacks/values/kratos-selfservice-ui-node.yaml
- helm/charts/kratos-selfservice-ui-node/README.md
- helm/charts/kratos-selfservice-ui-node/templates/deployment.yaml
- helm/charts/kratos-selfservice-ui-node/templates/tests/test-connection.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
> fix: to correctly configure `BASE_PATH` for selfservice-ui chart

- hacks/values/kratos.yaml
- helm/charts/kratos/templates/service-admin.yaml
- helm/charts/kratos/values.yaml
Add possibility to customize kratos endpoint path for prometheus (the same way it is possible to do so in HYDRA)
- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ x] I have referenced an issue containing the design document if my change introduces a new feature.
- [ x] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security vulnerability. 
- [ x] I have added tests that prove my fix is effective or that my feature works.
- [ x] I have added the necessary documentation within the code …
> feat: add template value for kratos metric path

- hacks/helm-validate.sh
- hacks/servicemonitor_v1.json
- hacks/values/hydra.yaml
- hacks/values/kratos.yaml
- helm/charts/hydra/templates/service-admin.yaml
- helm/charts/hydra/values.yaml
- helm/charts/kratos/templates/service-admin.yaml
- helm/charts/kratos/values.yaml
Remove the `.Capabilities.APIVersions.Has "monitoring.coreos.com/v1"` check done before enabling the service monitor
as this test will always fail
To avoid breaking changes, the default value for `.Values.serviceMonitor.enabled` is set to false.
- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ x] I have referenced an issue containing the design document if my change introduces a new feature.
- [ x] I have read the [security policy](../security/policy).
- [ x] I confirm that this pull request does not address a security vulnerability. 
- [ x] I have …
> fix: disable monitoring.coreos.com/v1 api check

- docs/helm/kratos.md
- hacks/values/kratos-selfservice-ui-node.yaml
- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/deployment-watcher.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/templates/job-migration.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos-selfservice-ui-node/templates/_helpers.tpl
- helm/charts/kratos-selfservice-ui-node/templates/deployment.yaml
- helm/charts/kratos-selfservice-ui-node/templates/secret.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/templates/cleanup-cron-job.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/deployment-watcher.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper-maester/values.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/values.yaml
- Address doc issue https://github.com/ory/k8s/issues/575
> feat: expand default secContext

- helm/charts/oathkeeper/templates/deployment-controller.yaml
This fix ensures that the oathkeeper controller deployment template correctly accounts for optional creation of configmap and secrets based on the provided values:
- `oathkeeper.secret.enabled`
- `secret.enabled`
n/a (couldn't find an open/closed issue for the controller failing to initialize due to configmap missing for rules)
this pr assumed that it should be possible to deploy the maester as a controller whilst also allowing it to manage the access rules. if this is incorrect, im happy to adjust the logic to ensure that the configmap for access rules get created unles *both* `managedAccessRules` is …
> fix: ensure oathkeeper controller deployment correctly account for optionally created resources.

- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra/values.yaml
Helm chart 0.41.0 requires commenting out the `hydra-maester.adminService.port` value. 
Test: 
`helm template ory/hydra` (port empty in maester Deployment args)
`helm template ory/hydra --set hydra-maester.adminService.port=null`  (child chart's default respected when "unset" in parent chart)
> fix: `hydra-maester.adminService.port` empty value is passed into child chart, causes error.

- docs/helm/hydra.md
- docs/helm/keto.md
- docs/helm/kratos.md
- hacks/manifests/dsn-secret.yaml
- hacks/values/kratos.yaml
- helm/charts/keto/templates/_helpers.tpl
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/templates/job-migration.yaml
- helm/charts/kratos/templates/_helpers.tpl
- helm/charts/kratos/templates/cleanup-cron-job.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
> feat: allow dsn to be configured optionally

- hacks/values/hydra.yaml
- helm/charts/hydra/README.md
- helm/charts/hydra/templates/job-migration.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/job-migration.yaml
- Followup to https://github.com/ory/k8s/pull/677
> feat: unify automigrate resources across charts

- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/job-migration.yaml
> fix: mount secrets to initContainer as well

- helm/charts/hydra-maester/Chart.yaml
- helm/charts/hydra-maester/README.md
- helm/charts/hydra-maester/crds/crd-oauth2clients.yaml
- helm/charts/hydra-maester/values.yaml
Relates to https://github.com/ory/hydra-maester/pull/145
> feat: implement token lifespans config from hydra-maester

- helm/charts/kratos/values.yaml
spend 8+ hours looking why my verifications emails where not styled when enabling the example settings commented out in valyes.yaml of kratos. fixed after a long time searching.
`verficication` now apparently is `verification_code`
solves confusion around #690 
> fix: update values.yaml change varification to verification_code

- helm/charts/kratos/Chart.yaml
- helm/charts/kratos/values.yaml
> chore: upgrade kratos image to v1.2.0

- hacks/values/oathkeeper.yaml
- helm/charts/oathkeeper/templates/_helpers.tpl
- helm/charts/oathkeeper/templates/configmap-rules.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/values.yaml
This patch changes the default value `maester.enabled` to `false`. If the user would like to manage the rules with the maester controller, `maester.enabled` should be set to `true` and `managedAccessRules` should be set to `false`
Fixes #512
Tested with the following configurations:
1- The user would like to manage rules manually. In this configuration the rules configmap and the initContainer to fix the permissions are not added to the deployment. rules volume is an emptydir:
```
oathkeeper:
managedAccessRules: false
maester:
enabled: false
```
2- The rules are managed by the helm chart …
> fix: disable maester by default

- helm/charts/kratos-selfservice-ui-node/README.md
- helm/charts/kratos-selfservice-ui-node/templates/service.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
Add support for `enabled`, `labels`, and `annotations` to the `kratos-selfservice-ui-node` Kubernetes Service.
N/A
This brings the features of this chart in line with other Ory Helm charts.
Local validation performed with:
```sh
helm template kratos-ui . -s templates/service.yaml
helm template kratos-ui . -s templates/service.yaml --set 'service.enabled=false'
helm template kratos-ui . -s templates/service.yaml --set 'service.labels.foo=bar'
helm template kratos-ui . -s templates/service.yaml --set 'service.annotations.foo=bar'
```
> feat: support enable, labels, and annotations for selfservice-ui service

- hacks/values/hydra.yaml
- hacks/values/keto.yaml
- hacks/values/kratos.yaml
- hacks/values/oathkeeper.yaml
- helm/charts/hydra/README.md
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/cleanup-cron-job.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/values.yaml
Similar to #703, it's useful to be able to template extra environment variables (especially `DSN`). For example, when using several Ory components and multiple environments you can template the DSNs to a shared value instead of needing to set each individually.
> feat: template extraEnv

- hacks/values/hydra.yaml
- hacks/values/keto.yaml
- hacks/values/oathkeeper.yaml
- helm/charts/hydra/templates/_helpers.tpl
- helm/charts/keto/templates/_helpers.tpl
- helm/charts/oathkeeper/templates/_helpers.tpl
- helm/charts/oathkeeper/templates/configmap-config.yaml
The Kratos chart allows templating the config settings in the chart values via the Helm `tpl` function, but the other charts don't allow this. Templating is very helpful for if you need to provide values which are based on other values in your environment, e.g. if parts of URLs include the `{{ .Release.Name }}` as they do with many 3rd party charts.
This PR includes:
- Keto: add `tpl` to the existing `keto.configmap` helper
- Hydra: add `tpl` to the existing `hydra.configmap` helper
- Oathkeeper: add a `oathkeeper.configmap` helper which behaves the same as the other charts
> feat: template configmaps

- helm/charts/example-idp/README.md
- helm/charts/example-idp/values.yaml
- helm/charts/hydra-maester/README.md
- helm/charts/hydra-maester/values.yaml
- helm/charts/hydra/README.md
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/values.yaml
- helm/charts/kratos-selfservice-ui-node/README.md
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper-maester/README.md
- helm/charts/oathkeeper-maester/values.yaml
> chore: upgrade images in charts

- helm/charts/hydra/README.md
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/values.yaml
> fix: make default probe timers less aggressive

- helm/charts/hydra-maester/README.md
- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
Add a `deployment.extraEnv` value to the hydra-maester helm chart for setting environment variables.
Fixes #650.
I followed the example of the hydra chart, using the same variable name.
> feat: allow setting env vars for hydra-maester

- helm/charts/hydra-maester/README.md
- helm/charts/oathkeeper/Chart.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/values.yaml
> chore: bump oathkeeper to 0.40.8

- helm/charts/hydra/templates/job-migrations-custom.yaml
Fixed version:
```
---
apiVersion: batch/v1
kind: Job
metadata:
name: ory-oel-hydra-oel-postgresql-ttl1
namespace: oasis
labels:
"app.kubernetes.io/name": "hydra"
"app.kubernetes.io/instance": "ory-oel-hydra"
"app.kubernetes.io/version": "v2.2.0"
"app.kubernetes.io/managed-by": "Helm"
"helm.sh/chart": "hydra-0.50.8"
annotations:
helm.sh/hook: pre-install, pre-upgrade
helm.sh/hook-delete-policy: before-hook-creation
helm.sh/hook-weight: "1"
spec:
template:
metadata:
annotations:
helm.sh/hook: pre-install, pre-upgrade
helm.sh/hook-delete-policy: before-hook-creation
helm.sh/hook-weight: "1"
labels:
app.kubernetes.io/name: ory-oel-hydra-oel-postgresql-ttl1-automigrate
app.kubernetes.io/instance: ory-oel-hydra
spec:
serviceAccountName: ory-oel-hydra-job
automountServiceAccountToken: true …
```
> chore: fix ident in custom migration job

- hacks/values/keto.yaml
- helm/charts/keto/templates/service-extraServices.yaml
- helm/charts/keto/templates/service-metrics.yaml
- helm/charts/keto/templates/service-read.yaml
- helm/charts/keto/templates/service-write.yaml
- helm/charts/keto/values.yaml
I have checked the other charts as well, and they already implement this.
> feat: allow service annotations in keto

- hacks/values/hydra.yaml
- helm/charts/hydra/templates/_helpers.tpl
- helm/charts/hydra/templates/ingress-admin.yaml
- helm/charts/hydra/templates/ingress-public.yaml
This PR will implement:
- helm templating of hostname in admin and public Ingress Resources for Hydra helm chart.
- helm templating of issuer as derived in _hydra.config.urls.issuer_ .
Note: 
Helm templating in ingress resources is already implemented in Kratos chart. This PR basically transfers all logic from the Kratos Ingress template to the Hydra chart.
> feat: allow helm templates in hostnames for hydra

- docs/helm/oathkeeper.md
In https://github.com/ory/k8s/commit/defbd626ad1f5357119b111a9a45d9a0dc2020e5 the behaviour of the oathkeeper chart was changed so that oathkeeper maester is disabled by default, this PR updates the docs to reflect this.
> docs: reflect that oathkeeper maester is disabled by default

- hacks/manifests/sa-deploy.yaml
- hacks/manifests/sa-job.yaml
- hacks/values/hydra/existing-service-accounts.yaml
- helm/charts/hydra/templates/_helpers.tpl
As described in #767, this pull request will allow to use an existing Kubernetes service account for job when not creating it through the chart.
```yaml
hydra:
automigration:
enabled: true
deployment:
serviceAccount:
create: false
name: "hydra-deploy-sa"
job:
serviceAccount:
create: false
name: "hydra-job-sa"
```
fixes #767
> fix: hydra use job.serviceAccount.name when using an existing sa

- helm/charts/hydra-maester/Chart.yaml
The version of the hydra maester chart is not consistent, it remains at v0.0.36 whereas the version of hydra mester is v0.0.37.
to complete this PR : https://github.com/ory/k8s/pull/774
> fix: user correct hydra-maester chart version

- helm/charts/hydra/README.md
- helm/charts/hydra/templates/_helpers.tpl
- helm/charts/hydra/templates/secrets.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/_helpers.tpl
- helm/charts/keto/templates/secrets.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos-selfservice-ui-node/README.md
- helm/charts/kratos-selfservice-ui-node/templates/_helpers.tpl
- helm/charts/kratos-selfservice-ui-node/templates/secret.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/_helpers.tpl
- helm/charts/kratos/templates/secrets.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/templates/_helpers.tpl
- helm/charts/oathkeeper/templates/secrets.yaml
- helm/charts/oathkeeper/values.yaml
Helm hooks can be easily opt-out from any ory component's charts when creating Kubernetes Secret.
#770 
N/A
> fix: helm hooks can be opt-out on ory components

- helm/charts/kratos/Chart.yaml
I wanted to update kratos to 1.3.1, but then saw only the appVersion is not up to date yet.
Minor nitpick.
> chore(deps): appVersion

- hacks/values/hydra-maester/default.yaml
- hacks/values/hydra/default.yaml
- hacks/values/keto/default.yaml
- hacks/values/kratos/default.yaml
- helm/charts/hydra-maester/README.md
- helm/charts/hydra-maester/templates/service-monitor.yaml
- helm/charts/hydra-maester/values.yaml
- helm/charts/hydra/README.md
- helm/charts/hydra/templates/service-admin.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/servicemonitor-metrics.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/service-admin.yaml
- helm/charts/kratos/templates/svc-statefulset.yaml
- helm/charts/kratos/values.yaml
This pull request updates all Helm charts to support feat-relabeling and metric relabeling.
It introduces new configuration options that allow users to customize relabeling rules for Prometheus metrics
across all charts in a consistent way.
Fix: #805
> feat: add relabeling and metricRelabeling in serviceMonitor for all helm charts
