ory/k8s

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/security.md
- .github/ISSUE_TEMPLATE/support.md
- .github/pull_request_template.md
- CONTRIBUTING.md
Signed-off-by: aeneasr <aeneas@ory.sh>
> docs: Updates issue and pull request templates

- helm/charts/hydra/templates/_helpers.tpl
Closes #15 
Adds a fallback for the version label
> Ensure version is present in kubernetes manifest labels

- helm/charts/hydra/templates/deployment.yaml
> helm: Fix migration init container #23

- helm/charts/hydra/templates/configmap.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/templates/ingress-admin.yaml
- helm/charts/hydra/templates/ingress-public.yaml
- helm/charts/hydra/templates/secrets.yaml
- helm/charts/hydra/templates/service-admin.yaml
- helm/charts/hydra/templates/service-public.yaml
Describe and implement chart resource _namespacing_ practices in appropriate for OryOS.
As described in #19 the current state of this PR shows the `noop` approach.
> [Helm] Resource namespacing

- docs/helm/hydra.md
Signed-off-by: Gregory Hill <greg.hill@monax.io>
> fix install instructions

- .circleci/config.yml
- .circleci/helm-test.sh
> POC microk8

- docs/helm/README.md
- docs/helm/hydra-maester.md
- docs/helm/hydra.md
- helm/charts/hydra/charts/hydra-maester/.helmignore
- helm/charts/hydra/charts/hydra-maester/Chart.yaml
- helm/charts/hydra/charts/hydra-maester/files/crd-oauth2clients.yaml
- helm/charts/hydra/charts/hydra-maester/templates/_helpers.tpl
- helm/charts/hydra/charts/hydra-maester/templates/crd-configmap.yaml
- helm/charts/hydra/charts/hydra-maester/templates/crd-job.yaml
- helm/charts/hydra/charts/hydra-maester/templates/crd-rbac.yaml
- helm/charts/hydra/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra/charts/hydra-maester/templates/rbac.yaml
- helm/charts/hydra/charts/hydra-maester/values.yaml
- helm/charts/hydra/requirements.yaml
- helm/charts/hydra/values.yaml
- Create skeleton for the hydra-maester chart
> Create chart skeleton for hydra-maester

- helm/charts/oathkeeper/charts/oathkeeper-master/templates/deployment.yaml
- helm/charts/oathkeeper/charts/oathkeeper-master/values.yaml
- helm/charts/oathkeeper/values.yaml
* bump oathkeeper and oathkeeper maester images
* use proper annotations from values
* add configurable environment variables to oathkeeper-maester deployment
> helm: Bump oathkeeper and oathkeeper maester images

- docs/helm/hydra-maester.md
- helm/charts/hydra/charts/hydra-maester/templates/rbac.yaml
https://github.com/ory/hydra-maester/pull/19
update Hydra-maester docu to reflect changes implemented in https://github.com/ory/hydra-maester/pull/19
> update Hydra-maester docu to reflect recent changes + rbac fix

- helm/charts/hydra/templates/deployment.yaml
fixes #52
As discussed with @aeneasr proposed fix is to fix it in both k8s charts and internally in hydra.
Adding volume mount for config from `configMap` and giving `--config` args for autoMigrate container to prevent it from crashing if no `--config` is given.
> fix: automigrate crashing without config given

- .circleci/config.yml
Enable RBAC in microk8s to properly test charts
> Enable rbac

- helm/charts/oathkeeper/templates/configmap-rules.yaml
Closes https://github.com/ory/oathkeeper/issues/274
> helm: Properly indent access rules

- helm/charts/example-idp/templates/ingress.yaml
- helm/charts/hive-selfservice-ui-node/templates/ingress.yaml
- helm/charts/hive/templates/ingress-admin.yaml
- helm/charts/hive/templates/ingress-public.yaml
- helm/charts/hydra/templates/ingress-admin.yaml
- helm/charts/hydra/templates/ingress-public.yaml
- helm/charts/oathkeeper/templates/ingress-api.yaml
- helm/charts/oathkeeper/templates/ingress-proxy.yaml
> helm: Reverse path quoting

- helm/charts/hive-selfservice-ui-node/templates/deployment.yaml
- helm/charts/hive-selfservice-ui-node/values.yaml
> helm/hivess: Add baseUrl config option

- helm/charts/hydra/templates/_helpers.tpl
- helm/charts/hydra/templates/configmap.yaml
#47 #75 
This replaces the `dsn` property in the config object with "redacted" when setting up the ConfigMap for the other settings
> redact dsn and secrets from config when setting up ConfigMap

- helm/charts/hive/templates/_helpers.tpl
- helm/charts/hive/templates/configmap-config.yaml
- helm/charts/hive/templates/deployment.yaml
- helm/charts/hive/templates/secrets.yaml
- helm/charts/hive/values.yaml
Closes https://github.com/ory/hive/issues/88
> helm/hive: Omit secrets from configmap

- docs/helm/hydra-maester.md
- helm/charts/hydra/charts/hydra-maester/files/crd-oauth2clients.yaml
Related to ory/hydra-maester#30
Updates the CRD documentation and manifest files
You can test the changes in conjunction with the updated hydra-maester by using `dangersalad/hyrda-maester:0.0.5-alpha7` for the hydra-maester image when deploying the chart
> update CRD doc and manifest

- docs/helm/oathkeeper.md
- helm/charts/oathkeeper/charts/oathkeeper-master/templates/deployment.yaml
- helm/charts/oathkeeper/charts/oathkeeper-master/values.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/values.yaml
- Update `oathkeeper` and `oathkeeper-maester` charts with the sidecar mode
- Update docs
- Implements https://github.com/ory/oathkeeper-maester/issues/21
> Create sidecar mode for ory oathkeeper

- helm/charts/oathkeeper/charts/oathkeeper-master/templates/deployment.yaml
- helm/charts/oathkeeper/charts/oathkeeper-master/values.yaml
- helm/charts/oathkeeper/values.yaml
- Bump images
- Update commands
> Update deployment and image

- docs/helm/hydra-maester.md
[#hydra-maester/20](https://github.com/ory/hydra-maester/issues/20)
Add a note about OwnerReference on Secrets created by Hydra Maester. 
> Add a note about OwnerReference on Secrets created by Hydra Maester

- helm/charts/hydra/charts/hydra-maester/files/crd-oauth2clients.yaml
- helm/charts/hydra/charts/hydra-maester/values.yaml
- helm/charts/oathkeeper/charts/oathkeeper-master/files/crd-rules.yaml
- helm/charts/oathkeeper/charts/oathkeeper-master/values.yaml
Simply bump the maesters and their CRDs with up-to date version taken from their respective repository
> chore: Bump maesters CRDs and version

- .circleci/config.yml
- .circleci/helm-test.sh
> Resolve CI bugs

- helm/charts/hydra-maester/files/crd-oauth2clients.yaml
docs/helm/hydra-maester.md describes a CR as namespaced, this commit
makes it explicit in the CRD.
#146 
the changes.
> fix: use explicit scope for hydra-maester CRD

- docs/helm/README.md
- docs/helm/kratos.md
> docs(Kratos): Add initial Kratos docs

- helm/charts/example-idp/templates/deployment.yaml
- helm/charts/example-idp/values.yaml
https://github.com/ory/hydra-login-consent-node/pull/59
Add BASE_URL support for example-idp. This introduces a new configurable value for the helm chart.
the changes.
None.
> feat: Add BASE_URL support for example-idp

- helm/charts/hydra/templates/deployment.yaml
> fix: use dedicated secret name

- helm/charts/hydra/templates/deployment.yaml
None
Fix the toleration indent on hydra deployment
- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [ x] I have read the [security policy](../security/policy)
- [ x] I confirm that this pull request does not address a security
the changes.
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] I have added necessary documentation within the code base (if appropriate)
> fix: tolerations indent in hydra deployment

- helm/charts/hydra/Chart.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/templates/ingress-admin.yaml
- helm/charts/hydra/templates/ingress-public.yaml
Updated to hydra 1.7.4 - Change init postgres container to migrate db with latest version
Also updated schema for ingress
the changes.
Tested and verified working.
> fix: Update to hydra helm chart to version 1.7.4

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/closed_references.yml
- .github/workflows/labels.yml
- .github/workflows/stale.yml
- CONTRIBUTING.md
- SECURITY.md
Updated repository templates to https://github.com/ory/meta/commit/ddb4d3dedae5de26fb5db83fabf491fe58735e67.
> chore: update repository template to ddb4d3de

- .github/workflows/closed_references.yml
- .github/workflows/labels.yml
- .github/workflows/stale.yml
- .reference-ignore
Updated repository templates to https://github.com/ory/meta/commit/7900d6c75a8a6e5f583591d5110eacacda1ef286.
> chore: update repository template to 7900d6c7

- helm/charts/kratos/Chart.yaml
- helm/charts/kratos/templates/configmap-config.yaml
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/values.yaml
> feat(kratos): support mounting identity schemas

- helm/charts/example-idp/templates/deployment.yaml
- helm/charts/example-idp/values.yaml
- helm/charts/hydra/templates/hpa.yaml
- helm/charts/hydra/values.yaml
the changes.
works.
appropriate).
> feat: add HPA for hydra +  mockTlsTermination for example-idp

- helm/charts/hydra/templates/hpa.yaml
- helm/charts/hydra/values.yaml
the changes.
works.
appropriate).
> feat: specify resource metrics as percentages instead of  direct values for HPA

- Makefile
See #215
the changes.
works.
appropriate).
> feat: add keto

- .circleci/config.yml
- helm/charts/keto/values.yaml
the changes.
works.
appropriate).
> ci: add lint for keto

- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/values.yaml
Kratos helm chart has a missing configuration to add extra volumes and mount as [#162 ](https://github.com/ory/k8s/issues/162) for Hydra. I copy-pasted all the related changes to Kratos helm to have this funcitonality
Add extraVolumes and extraMounts to Values and Deployment file
- [ x ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [ x ] I have read the [security policy](../security/policy).
- [ x ] I confirm that this pull request does not address a security
the changes.
- [ x ] I have added tests that prove my fix is effective or that my feature …
> feat: Extra Volumes and Extra Mounts added to Kratos

- helm/charts/hydra/templates/service-admin.yaml
- helm/charts/hydra/templates/service-public.yaml
- helm/charts/hydra/values.yaml
- helm/charts/oathkeeper/templates/service-api.yaml
- helm/charts/oathkeeper/templates/service-proxy.yaml
- helm/charts/oathkeeper/values.yaml
Be able to set service label from values.yaml.
This change was necessary because in order for [kiali](https://kiali.io/documentation/latest/features/#_graph_graph_types) to draw the graph correctly, both the deployment label and the service label need to be labeled with the same app.
the changes.
works.
appropriate).
> feat: set service label from values

- helm/charts/oathkeeper-maester/files/crd-rules.yaml
As indicated here https://github.com/ory/oathkeeper-maester/issues/43 upstream should not be required in CRD for Rules.
Already fixed it here: https://github.com/ory/oathkeeper-maester/pull/45.
This fix is now for the according helm chart
the changes.
works.
appropriate).
> fix: upstream should not be required in Rule CRD

- helm/charts/hydra-maester/crds/crd-oauth2clients.yaml
- helm/charts/oathkeeper-maester/crds/crd-rules.yaml
- Followup to https://github.com/ory/k8s/pull/235
- Implements https://github.com/ory/k8s/issues/236
In #235 we updated the CRD structure to be compliant to k8s 1.20 but introduced a bug with our served version. The `oauth2client` and `rule` CRDs are still in `v1alpha1`, as we didn't update the versions on the controller side. 
the changes.
works.
appropriate).
> fix: Adjust api versions for crds

- helm/charts/kratos-selfservice-ui-node/Chart.yaml
- helm/charts/kratos-selfservice-ui-node/templates/_helpers.tpl
Fix #251 
the changes.
works.
appropriate).
> fix: fix kratos-selfservice-ui-node name helper

- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- Add `extraVolumes` and `extraVolumeMounts` fields to the chart
the changes.
works.
appropriate).
> feat: add extraVolumes support for keto deployment

- helm/charts/hydra/templates/job-migration.yaml
- helm/charts/keto/templates/job-migration.yaml
- helm/charts/kratos/templates/job-migration.yaml
https://github.com/ory/k8s/pull/259
https://github.com/ory/k8s/issues/257
This PR is an integration of https://github.com/ory/k8s/pull/259 and adds job annotations to the template as well.
_Sorry for not introducing this change in the previous PR._
the changes.
works.
appropriate).
> feat: add Job annotations to Job template

- helm/charts/hydra-maester/templates/rbac.yaml
#225 
Removed attribute namespace from roleBinding.roleRef that was causing the problem
the changes.
works.
appropriate).
> fix(hydra-maester): remove namespace in roleBinding.roleRef (#225)

- helm/charts/kratos/Chart.yaml
- helm/charts/kratos/templates/configmap-templates.yaml
- helm/charts/kratos/values.yaml
Fixes https://github.com/ory/kratos/issues/1351
> Add support for Kratos 0.6

- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/templates/job-migration.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos-selfservice-ui-node/templates/deployment.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper-maester/values.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/values.yaml
- Implements https://github.com/ory/k8s/issues/48#event-4781279243
Add `automountServiceAccountToken: false` as default value for all charts. Expose it via values to enable overwrite, if required. 
the changes.
works.
appropriate).
> fix: disable sa automount

- helm/charts/hydra/templates/job-migration.yaml
#273 
Add volume support to Hydra migration job.
the changes.
works.
appropriate).
> feat: Add volumes to Hydra migration job

- helm/charts/hydra-maester/crds/crd-oauth2clients.yaml
- Fixes https://github.com/ory/hydra-maester/issues/71
- Update CRD after controller update
the changes.
works.
appropriate).
> chore: update hydra-maester crd

- .circleci/values/kratos.yaml
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/templates/secrets.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/templates/statefulset-svc.yaml
- helm/charts/kratos/values.yaml
- Implements https://github.com/ory/k8s/pull/290
- Add courier statefulset
- Adjust values
the changes.
works.
appropriate).
> feat: Update kratos chart for v6+

- helm/charts/kratos/templates/_helpers.tpl
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
- Merge image.repository and image.tag into one string
the changes.
works.
appropriate).
- Format requirement by https://skaffold.dev/docs/pipeline-stages/deployers/helm/#image-configuration
> fix: change kratos image format

- helm/charts/hydra-maester/templates/pdb.yaml
- helm/charts/hydra-maester/values.yaml
- helm/charts/hydra/templates/pdb.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/pdb.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/templates/pdb.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper-maester/templates/pdb.yaml
- helm/charts/oathkeeper-maester/values.yaml
- helm/charts/oathkeeper/templates/pdb.yaml
- helm/charts/oathkeeper/values.yaml
- Add optional [PDB](https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1/#PodDisruptionBudgetSpec) to all charts.
- This can be used to protect the applications from being killed/evicted without assuring that a certain amount or percent of pods is kept alive.
the changes.
works.
appropriate).
> feat: add PDB to all charts

- helm/charts/oathkeeper-maester/templates/_helpers.tpl
- Fixes https://github.com/ory/k8s/issues/294
the changes.
works.
appropriate).
**Before this fix**
```yaml
---
operation: helm install oathkeeper-name-test ./helm/charts/oathkeeper -f .circleci/values/oathkeeper.yaml
rules_cm: oathkeeper-name-test-rules
maester_target: oathkeeper-name-rules
---
operation:  helm install oathkeeper ./helm/charts/oathkeeper -f .circleci/values/oathkeeper.yaml --debug
rules_cm: oathkeeper-rules
maester_target: oathkeeper-rules
```
**After this fix**
```yaml
---
operation: helm install oathkeeper-name-test ./helm/charts/oathkeeper -f …
```
> fix: simplify name generation

- helm/charts/keto/templates/job-migration.yaml
This PR adds support for images to be hosted on a private registry
Tested manually
security@ory.sh) from the maintainers to push
the changes.
works.
appropriate).
> feat(keto): include imagePullSecrets for job migration

- .circleci/values/hydra.yaml
- docs/helm/hydra.md
- helm/charts/hydra/templates/NOTES.txt
- helm/charts/hydra/templates/ingress-admin.yaml
- helm/charts/hydra/templates/ingress-public.yaml
- helm/charts/hydra/values.yaml
This PR make the Hydra ingress compatible with Kubernetes 1.18+.
The changes are breaking because helm chart value `ingress.[public|admin].paths`  has changed from a simple array to an array of objects.
The latest version of the Hydra helm chart doesn't work on Kubernetes 1.19+ and I think also from version 1.14+.
This, for example, is the error message on kubernetes 1.21.3:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
```
vulnerability. …
> feat(hydra): support kubernetes 1.18+

- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
https://github.com/ory/k8s/pull/231 added `extraInitContainers` to only the main deployment. These init-containers should probably have been added to both the migration job and courier so that mTLS can be setup correctly for these pods which also require access to the database (see the example in their PR)
I personally don't like that we're using `tpl` here instead of `toYaml` but I've kept it for consistency with the initContainer in the deployment. I can change it upon request.
Tested manually
CLA signed based on California's Labor Code Section 2870 Notice. (Employer non-assignable inventions)
Pull request: https://github.com/ory/k8s/pull/231 …
> feat(kratos): add initContainers to kratos courier + migrations

- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
https://github.com/ory/k8s/pull/300 Added support for init-containers, but the way they were implemented led helm to interpret them as strings instead of as yaml. This was an error of communication between author and reviewer.
Example of how this is currently parsed:
```
initContainers:
|
- command: ...
```
I'm not sure why exactly the bar gets added but it does
the changes.
works.
appropriate).
> fix(kratos): correct initContainer formatting

- .circleci/values/kratos.yaml
Add hello world init container to kratos to have the CI verify templating 
- Followup to https://github.com/ory/k8s/pull/310
the changes.
works.
appropriate).
> chore: update kratos.yaml

- .github/CODEOWNERS
I would like to introduce myself to code owner in this repository to help @Demonsthere manage it.
the changes.
works.
appropriate).
> chore: add additional codeowner

- helm/charts/kratos/values.yaml
In the `value.yml` file, there are examples related to email templates definition. In the section `verification` of examples, the variable is wrongly the `RecoveryURL` instead of `VerificationURL`
the changes.
works.
appropriate).
> docs: fix variable name in email templates examples

- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/hpa.yaml
- helm/charts/kratos/values.yaml
This change fixes https://github.com/ory/k8s/issues/318 
the changes.
works.
appropriate).
> fix(hpa): remove problematic explicit setting of replica counts in deployments

- helm/charts/hydra-maester/README.md
- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
This PR allows configuring the sync-period command line parameter of hydra-maester.
https://github.com/ory/hydra-maester/blob/028c3df4c2b8455f4f0fba27e11507490b140590/main.go#L62
the changes.
works.
appropriate).
> feat(hydra-maester): Allow configuration of the sync-period parameter.

- .circleci/config.yml
- Makefile
- helm/charts/hydra-maester/Chart.yaml
- helm/charts/hydra/Chart.yaml
- helm/charts/keto/Chart.yaml
- helm/charts/kratos/Chart.yaml
- helm/charts/oathkeeper-maester/Chart.yaml
- helm/charts/oathkeeper/Chart.yaml
- Move some logic from CI to makefile
- Add helm-docs pipeline
- Fixes https://github.com/ory/k8s/issues/323
the changes.
works.
appropriate).
> chore: update makefile

- .github/workflows/stale.yml
- LICENSE
Updated repository templates to https://github.com/ory/meta/commit/455ef8896cd7ddfa08f4c2b8325c528bcdb65762.
> chore: update repository template to 455ef889

- .circleci/values/oathkeeper-maester.yaml
- helm/charts/hydra-maester/values.yaml
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper-maester/values.yaml
the changes.
works.
appropriate).
> chore: Update maester versions

- .circleci/config.yml
- .circleci/helm-test.sh
- .circleci/helm-upgrade.sh
- Makefile
Add pipeline for upgrade testing (install release from repository, upgrade to current local version, perform connection test)
The test is not any way sophisticated, but should allow us to detect critical problems between version (such a chart breaking compatibility, and not installing).
- Implements #309 
the changes.
works.
appropriate).
> feat: Introduce upgrade pipeline

- helm/charts/hydra/values.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/values.yaml
the changes.
works.
appropriate).
> chore: bump watcher image

- .circleci/config.yml
- LICENSE
- README.md
the changes.
works.
appropriate).
> fix: revert overriden files

- helm/charts/hydra/templates/service-admin.yaml
- helm/charts/hydra/templates/service-public.yaml
- helm/charts/hydra/values.yaml
- helm/charts/kratos-selfservice-ui-node/templates/service.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/templates/service-admin.yaml
- helm/charts/kratos/templates/service-public.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/service-api.yaml
- helm/charts/oathkeeper/templates/service-proxy.yaml
- helm/charts/oathkeeper/values.yaml
This change comes from a very specific pain point of using Istio and and `passthrough` TLS, and having Oathkeeper specifically terminate the TLS certificates at the pod. Istio requires the port name to follow [a specific naming convention](https://istio.io/latest/docs/reference/config/analysis/ist0118/). When in the configuration of the passing https traffic to the service port, since the port is named `http`, it is in violation and Istio does not route the traffic.
This allows a user to optionally set the `service.proxy.portName: https` to be in compliance with Istio.
This is mostly for the proxy port, but to be consistent I have also set a `portName` value for the API service.
N/A
vulnerability. If this pull request addresses a security …
> feat: Making service port names configurable

- .circleci/helm-test.sh
- .circleci/helm-upgrade.sh
the changes.
works.
appropriate).
> chore: simplify release names in tests

- .circleci/helm-test.sh
- .circleci/helm-upgrade.sh
- .circleci/values/kratos.yaml
- helm/charts/kratos-selfservice-ui-node/Chart.yaml
- helm/charts/kratos-selfservice-ui-node/templates/deployment.yaml
- helm/charts/kratos-selfservice-ui-node/templates/tests/test-connection.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/Chart.yaml
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/values.yaml
- Update kratos and kratos-selfservice to work alongside kratos release 0.8
the changes.
works.
appropriate).
> fix: Make kratos and selfservice work in 0.8

- helm/charts/keto/Chart.yaml
- helm/charts/keto/templates/job-migration.yaml
- helm/charts/keto/values.yaml
In Keto we removed the `--all-namespaces` flag.
the changes.
works.
appropriate).
> chore: bump Keto version and adjust migrate command

- .circleci/values/hydra.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/templates/job-migration.yaml
- helm/charts/hydra/values.yaml
Add ability to use custom init containers to hydra. This is helpful when using a custom PKI system when talking with cockroachdb.
Tested manually
Pull request [#300](https://github.com/ory/k8s/pull/300)
Pull request [#310](https://github.com/ory/k8s/pull/310)
the changes.
works.
appropriate).
> feat(hydra): Add initContainers to hydra

- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
Add imagePullSecrets to the statefulset and job. For some reason they were missing
- Fixes https://github.com/ory/k8s/issues/365
the changes.
works.
appropriate).
> fix: Add imagePullSecrets to other kratos elements

- helm/charts/kratos/templates/deployment.yaml
- Fix https://github.com/ory/k8s/issues/349
the changes.
works.
appropriate).
> fix: Allow kratos to preload secret

- .circleci/values/kratos.yaml
- Makefile
- helm/charts/kratos/templates/_helpers.tpl
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/secrets.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- Add cipher to managed secrets
- Fixes https://github.com/ory/k8s/issues/374
the changes.
works.
appropriate).
> fix: Add cipher to kratos secret

- .circleci/values/kratos.yaml
- docs/helm/hydra.md
- docs/helm/kratos.md
- Update docs for hydra
- Update docs for kratos
- Fixes https://github.com/ory/k8s/issues/367
- Fixes https://github.com/ory/k8s/issues/373
the changes.
works.
appropriate).
> docs: Update outdated entries in docs

- helm/charts/hydra-maester/values.yaml
- helm/charts/oathkeeper-maester/values.yaml
the changes.
works.
appropriate).
> chore: upgrade maester images

- .circleci/values/kratos.yaml
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/values.yaml
- add `extraArgs` to the deployment, which allow adding custom cmd arguments
- Implement feature requested in https://github.com/ory/k8s/pull/375
the changes.
works.
appropriate).
> feat: add extraArgs to kratos

- helm/charts/kratos/templates/statefulset-mail.yaml
the changes.
works.
appropriate).
> fix: Propagate deployment labels to courier pod

- .circleci/values/kratos.yaml
- helm/charts/kratos/templates/_helpers.tpl
- Import improved secret parsing from hydra
- Followup to https://github.com/ory/k8s/pull/376
the changes.
works.
appropriate).
> fix: improve array parsing for kratos

- .circleci/values/keto.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
the changes.
works.
appropriate).
> feat: add extraLabels to keto

- .circleci/values/kratos.yaml
- helm/charts/kratos/templates/job-migration.yaml
- Add missing lablels to kratos migration job
the changes.
works.
appropriate).
> fix: add labels to kratos migration

- helm/charts/hydra-maester/templates/rbac.yaml
- helm/charts/oathkeeper-maester/templates/rbac.yaml
Removing namespace from ClusterRole and ClusterRoleBinding in the oathkeeper-maester and hydra-maester, as these are not-namespaced resources, which can cause errors when applying those Helm templates.
the changes.
works.
appropriate).
> fix: remove namespace reference from ClusterRole and ClusterRoleBinding

- docs/helm/kratos.md
- fix: update custom secrets howto
- chore: format
https://github.com/ory/kratos/discussions/2077
the changes.
works.
appropriate).
> fix: update custom secret howto

- .circleci/values/keto.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
the changes.
works.
appropriate).
> feat: add custom annotations to keto deployment

- helm/charts/kratos/templates/service-admin.yaml
- helm/charts/kratos/templates/service-public.yaml
- helm/charts/kratos/values.yaml
Implements #388 
the changes.
works.
appropriate).
> feat: Add component label to kratos svcs

- helm/charts/kratos/templates/service-admin.yaml
- helm/charts/kratos/templates/service-public.yaml
- helm/charts/kratos/templates/statefulset-svc.yaml
the changes.
works.
appropriate).
> feat: add prometheus service monitor to kratos

- .circleci/values/hydra.yaml
- .circleci/values/keto.yaml
- .circleci/values/kratos.yaml
- .circleci/values/postgres.yaml
- helm/charts/kratos/templates/service-admin.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/templates/service-api.yaml
- helm/charts/oathkeeper/templates/service-metrics.yaml
- helm/charts/oathkeeper/templates/service-proxy.yaml
- helm/charts/oathkeeper/values.yaml
- Add dedicated service for oathkeeper-metrics
- Add condiitonal ServiceMonitor
- Add missing label to kratos
the changes.
works.
appropriate).
> feat: add metrics service to oathkeeper

- .circleci/values/oathkeeper.yaml
- helm/charts/keto/Chart.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/templates/service-metrics.yaml
- helm/charts/keto/templates/service-write.yaml
- helm/charts/keto/templates/servicemonitor-metrics.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/oathkeeper/Chart.yaml
- helm/charts/oathkeeper/values.yaml
This PR adds the new metrics endpoint and ServiceMonitor to the keto chart
- Requires https://github.com/ory/keto/pull/832 to be merged and released
the changes.
works.
appropriate).
> feat: add metrics service

- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper-maester/values.yaml
Add missing configuration to charts
- Fixes https://github.com/ory/k8s/issues/399
the changes.
works.
appropriate).
> fix: add missing pullsecrets to maesters

- helm/charts/kratos/templates/deployment.yaml
Replace https://github.com/ory/k8s/pull/403
Fix https://github.com/ory/k8s/issues/402
the changes.
works.
appropriate).
No breaking changes
> fix: update resource decalaration in deployment template

- helm/charts/keto/templates/job-migration.yaml
- helm/charts/keto/values.yaml
the changes.
works.
appropriate).
> fix: add missing values to keto

- helm/charts/keto/templates/deployment.yaml
the changes.
works.
appropriate).
> fix: broken keto volumesMounts

- helm/charts/kratos/templates/ingress-admin.yaml
- helm/charts/kratos/templates/ingress-public.yaml
the changes.
works.
appropriate).
> fix: Unable to access service through ingress

- .circleci/helm-upgrade.sh
- .circleci/values/kratos.yaml
- helm/charts/kratos/Chart.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/service-admin.yaml
- helm/charts/kratos/templates/tests/test-connection.yaml
- helm/charts/kratos/values.yaml
the changes.
works.
appropriate).
> feat: Upgrade kratos chart to releaser 0.9.0

- .circleci/helm-upgrade.sh
the changes.
works.
appropriate).
> fix: upgrade ci

- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
It is currently not possible to add annotations to the kratos courier pod.
This PR adds annotations to the kratos courier statefulset spec template. Following the current behavior, it reuses the `deployment.annotations` config, which is also used  to annotate the kratos deployment and spec as well as the courier statefulset itself.
- ~I have referenced an issue containing the design document if my change
introduces a new feature.~ No Issues was opened, since I the PR was already implemented for our use case.
the changes.
- ~I have added tests that prove my fix is effective or …
> feat: add custom annotations to kratos courier

- docs/helm/hydra.md
Fix #430
the changes.
works.
appropriate).
> fix: Expected hydra.config.secrets.system to be a list of strings

- helm/charts/kratos/templates/statefulset-mail.yaml
The Kratos Courier stateful set doesn't include the ServiceAccountName, whereas is exists only on the Kratos deployment.  Fixes #434
the changes.
works.
appropriate).
> Addition of serviceAccountName on Kratos Courier - Fixes #434

- helm/charts/hydra/values.yaml
This configuration file was moved: https://github.com/ory/hydra/pull/1782/files?file-filters%5B%5D=.yaml&show-viewed-files=true#diff-354af1369f3fccd0133ec87bf2a28b39ee813c7f7bd34115d8b6d2d2f2ce4b41
the changes.
works.
appropriate).
> Fix broken configuration YAML link

- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
Allow specifying init containers for keto.
maintainers to push the changes.
> allow init containers in keto

- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/templates/ingress-read.yaml
- helm/charts/keto/templates/ingress-write.yaml
- helm/charts/keto/templates/service-metrics.yaml
- helm/charts/keto/templates/service-read.yaml
- helm/charts/keto/templates/service-write.yaml
- helm/charts/keto/values.yaml
- Fixes https://github.com/ory/k8s/issues/445
> feat: set grpc as default names for keto services

- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/hpa-controller.yaml
- helm/charts/oathkeeper/values.yaml
Add horizontal pod autoscaler to oathkeeper helm chart. Oathkeeper can be scaled based on memory and (or) cpu utilization.
> feat: add horizontal pod autoscaler to oathkeeper helm chart

- helm/charts/hydra/templates/job-migration.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/job-migration.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/values.yaml
- Implements https://github.com/ory/k8s/issues/425
> feat: add nodeSelectors to migration jobs

- helm/charts/hydra/Chart.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/Chart.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/Chart.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/Chart.yaml
- helm/charts/oathkeeper/values.yaml
> chore: update image versions for core components

- .circleci/values/hydra.yaml
- .circleci/values/keto.yaml
- .circleci/values/kratos.yaml
- helm/charts/kratos/templates/job-migration.yaml
Before changes templating was failing if extra volumemounts are used with following error : 
```
Error: YAML parse error on kratos/templates/job-migration.yaml: error converting YAML to JSON: yaml: line 69: did not find expected key Use --debug flag to render out invalid YAML
```
and rendered output was : 
```
volumeMounts:
- name: kratos-config-volume
mountPath: /etc/config
readOnly: true
- mountPath: /etc/xyz
name: cert-volume
readOnly: true
```              
> fix: indent in kratos migration job template

- .github/workflows/ci.yml
> ci: fix release job process

- .github/workflows/ci.yml
@AlexandreBrg @Demonsthere @piotrmsc please don't use my work email in git.
> fix: update user

- .github/workflows/ci.yml
- Makefile
- hacks/manifests/cm-sample.yaml
- hacks/values/hydra.yaml
- hacks/values/keto.yaml
- hacks/values/kratos.yaml
- helm/charts/hydra/files/watch.sh
- helm/charts/hydra/templates/deployment-watcher.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/templates/rbac-watcher.yaml
- helm/charts/hydra/templates/rbac.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/files/watch.sh
- helm/charts/keto/templates/deployment-watcher.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/templates/rbac-watcher.yaml
- helm/charts/keto/templates/rbac.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/files/watch.sh
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/deployment-watcher.yaml
- helm/charts/kratos/templates/deployment.yaml
- helm/charts/kratos/templates/rbac-watcher.yaml
- helm/charts/kratos/templates/rbac.yaml
- helm/charts/kratos/values.yaml
- Fixes https://github.com/ory/k8s/issues/476
- Fixes bug where the probes were using port name instead of number, which caused an type conversion error
> feat: extract watcher sidecar to deployment

- hacks/values/kratos.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/values.yaml
> feat: allow custom probes for kratos

- .github/workflows/ci.yml
Full run of the pipeline with "forced" test of charts: https://github.com/AlexandreBrg/k8s/actions/runs/2782061515
Closes #467 
Closes #480
> ci: activate upgrade testing

- helm/charts/kratos/templates/configmap-config.yaml
- helm/charts/kratos/templates/configmap-migrate.yaml
- helm/charts/kratos/templates/configmap-templates.yaml
- helm/charts/kratos/values.yaml
> feat: add support to include annotations to kratos configmap

- hacks/values/oathkeeper.yaml
- helm/charts/oathkeeper/templates/service-metrics.yaml
- helm/charts/oathkeeper/values.yaml
> feat: add labels on ServiceMonitor

- hacks/values/kratos.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
Also fix capitalization in readme.md
Fix: #486
> feat(kratos): add statefulset.extraArgs option

- docs/helm/hydra.md
- docs/helm/keto.md
- docs/helm/kratos.md
- docs/helm/oathkeeper.md
Hey
just a little addition of the `helm repo add`and `helm repo update` commands
I had to search a bit to find that page: https://k8s.ory.sh/helm/
> docs: add a add-helm-repo section to installation

- hacks/values/oathkeeper.yaml
- helm/charts/oathkeeper/templates/service-metrics.yaml
fixes https://github.com/ory/k8s/pull/494
> chore: fix metricRelabelings

- hacks/values/kratos.yaml
- helm/charts/kratos/templates/configmap-templates.yaml
- helm/charts/kratos/values.yaml
- Fixes https://github.com/ory/k8s/issues/490
> fix: kratos email template rendering

- README.md
The tests are running on GitHub Actions now.
> ci: update badge from CircleCI to GitHub Actions

- docs/helm/kratos.md
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/configmap-config.yaml
- helm/charts/kratos/values.yaml
Use Helm tpl function to substitute file from values. Closes #505
I would like to write identities schema on separate file, not on `.Values.kratos.identitySchemas.<filename>.<json-schema>`.
Json schema locales on same directory which my values on. It allows me to use hints from my IDE. More details on linked issue
With PR linked to #505 issue. I use Helm tpl function to substitute template to file which are set using `--set-file` Helm CLI argument. Example described on issue
- [ x I have referenced an issue containing the design document if my change introduces a new feature.
> feat: tpl identitySchemas files

- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/values.yaml
Allow for settings extra configs
> feat: add extraArgs to oath chart

- hacks/values/keto.yaml
- helm/charts/keto/Chart.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/templates/service-extraServices.yaml
- helm/charts/keto/templates/service-metrics.yaml
- helm/charts/keto/templates/service-read.yaml
- helm/charts/keto/templates/service-write.yaml
- helm/charts/keto/values.yaml
> feat: allow for extra services and port

- hacks/values/hydra.yaml
- helm/charts/hydra/Chart.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/templates/service-admin.yaml
- helm/charts/hydra/values.yaml
> feat: use hydra v2 release

- .github/workflows/format.yml
The "format" CI task is stand-alone again.
> Kg remove format header

- helm/charts/kratos-selfservice-ui-node/Chart.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- Fixes https://github.com/ory/k8s/issues/539
> chore: update default image of kratos-selfservice-ui-node

- Makefile
- helm/charts/hydra/README.md
https://github.com/ory/cli/pull/257 changed the name of the command to add copyright headers to files.
> chore: update Ory CLI with breaking changes to the format task

- helm/charts/example-idp/templates/deployment.yaml
- helm/charts/example-idp/values.yaml
- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
- helm/charts/hydra/Chart.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos-selfservice-ui-node/templates/deployment.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper-maester/values.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/values.yaml
This small PR allows for specifying the [topologySpreadConstraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) for the Hydra deployment. This is useful when trying to spread the Hydra pods across availability zones.
> fix: hydra allow for specifying topologySpreadConstraints

- hacks/values/hydra.yaml
- hacks/values/keto.yaml
- hacks/values/kratos.yaml
- hacks/values/postgres.yaml
- helm/charts/hydra/files/watch.sh
- helm/charts/hydra/templates/_helpers.tpl
- helm/charts/hydra/templates/deployment-watcher.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/files/watch.sh
- helm/charts/keto/templates/_helpers.tpl
- helm/charts/keto/templates/deployment-watcher.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/files/watch.sh
- helm/charts/kratos/templates/_helpers.tpl
- helm/charts/kratos/templates/deployment-watcher.yaml
- helm/charts/kratos/templates/rbac-watcher.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
- Set separate databases for testing deployments
- Add dedicated labels for watcher
- Add watcher for kratos statefulset
> feat: watcher improvements

- helm/charts/oathkeeper/templates/hpa-controller.yaml
See argoproj/argo-cd#1079 - resources need to be in a different order for Argo to handle them successfully.
- [X I confirm that this pull request does not address a security vulnerability. 
> chore: order hpa metrics for Argo

- helm/charts/hydra/README.md
- helm/charts/hydra/templates/job-migration.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/job-migration.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/values.yaml
We need to have an ability to set tolerantions for Job entity because in other case it's impossible to make auto-migration pod in kube cluster where all nodes have the taints
> feat: add tolerations to job-migration

- Makefile
- helm/charts/hydra/README.md
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/values.yaml
> feat: add startupProbes to all charts

- helm/charts/hydra/values.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/values.yaml
> chore: update toolbox helper image

- helm/charts/hydra/Chart.yaml
- helm/charts/hydra/values.yaml
- helm/charts/kratos/Chart.yaml
- helm/charts/kratos/values.yaml
> chore: upgrade application versions

- helm/charts/oathkeeper/Chart.yaml
- helm/charts/oathkeeper/values.yaml
> chore: upgrade oathkeeper to 0.40.0

- hacks/values/hydra.yaml
- helm/charts/hydra/Chart.yaml
- helm/charts/hydra/templates/deployment-watcher.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/templates/janitor-cron-job.yaml
- helm/charts/hydra/templates/job-migration.yaml
- helm/charts/hydra/values.yaml
Signed-off-by: André Bauer <andre.bauer@staffbase.com>
* added securityContext & podSecurityContext to all containers
* used  {{ with }} instead of {{ if }} for all occurences for consistency reasons
* migration inti container uses same securityContext & podSecurityContext as hydra
* added resource requests and limit to automigrate initcontainer
> fix: [hydra helm chart] add missing securityContext in initcontainer

- helm/charts/oathkeeper/Chart.yaml
- helm/charts/oathkeeper/values.yaml
> chore: upgrade oathkeeper to 0.40.1

- helm/charts/hydra/templates/deployment.yaml
* fix init container resources (toYaml was missing)
* bug was introduced in: https://github.com/ory/k8s/pull/560
* not sure why the tests did not catch that: https://github.com/ory/k8s/blob/master/hacks/values/hydra.yaml#L13-L19
> fix: [hydra helm chart] init container resources

- helm/charts/kratos/README.md
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
- Fixes https://github.com/ory/k8s/issues/562
> chore: cleanup kratos values

- helm/charts/hydra/templates/hpa.yaml
- helm/charts/kratos/templates/hpa.yaml
Because of this [kubernetes issue](https://github.com/kubernetes/kubernetes/issues/74099) argocd see a perpetual diff on hpa for kratos and hydra.
By ordering memory target before cpu for kratos and hydra hpa, the diff in argocd will disapear without having to setup a ignorediff rule for those hpas.
[kubernetes issue](https://github.com/kubernetes/kubernetes/issues/74099)
[argocd issue](https://github.com/argoproj/argo-cd/issues/1079)
n/a
> fix: define memory target before cpu in hpa for kratos and hydra to avoid diff in argocd

- helm/charts/hydra/templates/service-admin.yaml
- helm/charts/hydra/templates/service-public.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/service-extraServices.yaml
- helm/charts/keto/templates/service-metrics.yaml
- helm/charts/keto/templates/service-read.yaml
- helm/charts/keto/templates/service-write.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos-selfservice-ui-node/templates/service.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/templates/service-admin.yaml
- helm/charts/kratos/templates/service-public.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/templates/service-api.yaml
- helm/charts/oathkeeper/templates/service-metrics.yaml
- helm/charts/oathkeeper/templates/service-proxy.yaml
- helm/charts/oathkeeper/values.yaml
> feat: add loadBalancerIP

- helm/charts/keto/templates/service-read.yaml
- helm/charts/keto/templates/service-write.yaml
- helm/charts/keto/values.yaml
> fix: set appProtocol for keto services

- hacks/values/oathkeeper.yaml
- helm/charts/oathkeeper/Chart.yaml
- helm/charts/oathkeeper/values.yaml
> chore: bump oathkeeper

- hacks/manifests/env-secrets.yaml
- hacks/values/kratos.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
This pull requests adds support of environmentSecretsName for karpenter-courier and fixing following problem:
helm chart kratos does not implement loading environment variable from file for courier #588
> fix: environmentSecretsName for kratos courier 

- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/values.yaml
> feat: add lifecycle values

- helm/charts/oathkeeper-maester/Chart.yaml
- helm/charts/oathkeeper-maester/crds/crd-rules.yaml
- helm/charts/oathkeeper-maester/values.yaml
> feat: upgrading oathkeeper-maester version and CRD

- .prettierignore
- helm/charts/example-idp/Chart.yaml
- helm/charts/example-idp/README.md
- helm/charts/example-idp/values.yaml
- helm/charts/hydra-maester/values.yaml
- helm/charts/hydra/Chart.yaml
- helm/charts/hydra/README.md
- helm/charts/hydra/values.yaml
- helm/charts/keto/Chart.yaml
- helm/charts/keto/README.md
- helm/charts/keto/values.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/Chart.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper-maester/Chart.yaml
- helm/charts/oathkeeper-maester/README.md
- helm/charts/oathkeeper-maester/values.yaml
- helm/charts/oathkeeper/Chart.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/demo/access-rules.json
- helm/charts/oathkeeper/values.yaml
- Closes https://github.com/ory/k8s/issues/590
> chore: update ory components

- hacks/values/hydra.yaml
- hacks/values/keto.yaml
- hacks/values/oathkeeper.yaml
- helm/charts/example-idp/Chart.yaml
- helm/charts/hydra/templates/tests/test-connection.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/tests/test-connection.yaml
- helm/charts/keto/values.yaml
- helm/charts/oathkeeper-maester/Chart.yaml
- helm/charts/oathkeeper/templates/tests/test-connection.yaml
- helm/charts/oathkeeper/values.yaml
> feat: allow user defined labels via values file for test pods

- .github/actions/deps-setup/action.yaml
- .github/workflows/ci.yml
- .github/workflows/licenses.yml
> chore: update gha

- hacks/values/example-idp.yaml
- hacks/values/hydra.yaml
- hacks/values/keto.yaml
- hacks/values/kratos-selfservice-ui-node.yaml
- hacks/values/kratos.yaml
- hacks/values/oathkeeper.yaml
- helm/charts/example-idp/templates/tests/test-connection.yaml
- helm/charts/example-idp/values.yaml
- helm/charts/hydra/templates/tests/test-connection.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/tests/test-connection.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos-selfservice-ui-node/templates/tests/test-connection.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/templates/tests/test-connection.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/templates/tests/test-connection.yaml
- helm/charts/oathkeeper/values.yaml
Allow the charts to be used in environments with constraints on connectivity to container image repositories.
A hard-coded name `busybox` means that the Chart tests rely on the Kubernetes cluster being able to pull from Docker Hub. We already allow the component image to be customised, so this follows the same pattern for the busybox image.
> feat: parameterise busybox image repo/tag

- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/templates/hpa.yaml
- helm/charts/keto/templates/pdb.yaml
This PR supersedes https://github.com/ory/k8s/pull/604 due to problems with the CLA
> fix: add missing ns to keto

- hacks/values/hydra.yaml
- helm/charts/example-idp/Chart.yaml
- helm/charts/example-idp/README.md
- helm/charts/hydra-maester/README.md
- helm/charts/hydra/README.md
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/kratos-selfservice-ui-node/README.md
- helm/charts/kratos/README.md
- helm/charts/oathkeeper-maester/Chart.yaml
- helm/charts/oathkeeper-maester/README.md
- helm/charts/oathkeeper/README.md
> chore: update hydra secContext

- docs/helm/kratos.md
> docs: update kratos.md

- README.md
- hacks/values/kratos.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/job-migration.yaml
- helm/charts/kratos/values.yaml
* added securityContext to init containers, similar to [this PR](https://github.com/ory/k8s/pull/560) for Hydra
* added resource requests and limit to automigrate initcontainer
* removed old `--cleanup` flag from helm test example and corrected the examples in Readme
* fixed some typos
> fix: add securityContext to kratos init containers

- .github/actions/deps-setup/action.yaml
- hacks/helm-validate.sh
- hacks/values/oathkeeper.yaml
> chore: migrate kubeval to kubeconform

- helm/charts/hydra/Chart.yaml
- helm/charts/hydra/README.md
- helm/charts/hydra/values.yaml
- helm/charts/keto/Chart.yaml
- helm/charts/keto/README.md
- helm/charts/kratos-selfservice-ui-node/Chart.yaml
- helm/charts/kratos-selfservice-ui-node/README.md
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/oathkeeper/Chart.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/values.yaml
> chore: bump versions

- hacks/values/kratos.yaml
- helm/charts/example-idp/README.md
- helm/charts/example-idp/templates/deployment.yaml
- helm/charts/example-idp/values.yaml
- helm/charts/hydra-maester/README.md
- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
- helm/charts/hydra/README.md
- helm/charts/hydra/templates/deployment-watcher.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/deployment-watcher.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos-selfservice-ui-node/README.md
- helm/charts/kratos-selfservice-ui-node/templates/deployment.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/deployment-watcher.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper-maester/README.md
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper-maester/values.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/values.yaml
> feat: add configurable revision history limit

- helm/charts/hydra-maester/Chart.yaml
- helm/charts/hydra-maester/README.md
- helm/charts/hydra-maester/crds/crd-oauth2clients.yaml
- helm/charts/hydra-maester/values.yaml
> feat: update hydra-maester to 0.0.29

- hacks/values/hydra.yaml
- helm/charts/hydra/README.md
- helm/charts/hydra/templates/janitor-cron-job.yaml
- helm/charts/hydra/values.yaml
> feat: add extraContainers and extraInitContainers to Hydra Janitor

- helm/charts/hydra-maester/README.md
- helm/charts/hydra-maester/values.yaml
- helm/charts/hydra/README.md
- helm/charts/oathkeeper-maester/README.md
- helm/charts/oathkeeper-maester/crds/crd-rules.yaml
- helm/charts/oathkeeper-maester/values.yaml
> chore: update maester imge formats

- hacks/values/hydra.yaml
- helm/charts/hydra/templates/_helpers.tpl
- Fixes https://github.com/ory/k8s/issues/643
```shell
kubectl get secrets/hydra --template={{.data.secretsSystem}} | base64 -d ; echo
"OG5XbmxXa3dYeGplQXpQanYxeEFuRUFa","foo bar 123 456 lorem","foo bar 123 456 lorem 1","foo bar 123 456 lorem 2","foo bar 123 456 lorem 3"
kubectl get secrets/hydra --template={{.data.secretsCookie}} | base64 -d ; echo
[OG5XbmxXa3dYeGplQXpQanYxeEFuRUFa foo bar 123 456 lorem foo bar 123 456 lorem 1 foo bar 123 456 lorem 2 foo bar 123 456 lorem 3]
kubectl get secrets/hydra --template={{.data.secretsCookie}} | base64 -d ; echo
"OG5XbmxXa3dYeGplQXpQanYxeEFuRUFa","foo bar 123 456 lorem","foo bar 123 456 lorem 1","foo bar 123 456 lorem 2","foo bar 123 456 lorem 3"
```
I confirm that I got approval (please …
> fix: unify secret handling for hydra

- helm/charts/hydra-maester/templates/deployment.yaml
- helm/charts/hydra-maester/values.yaml
- helm/charts/hydra/templates/deployment-watcher.yaml
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/templates/deployment-watcher.yaml
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos-selfservice-ui-node/templates/deployment.yaml
- helm/charts/kratos-selfservice-ui-node/values.yaml
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/templates/deployment-watcher.yaml
- helm/charts/kratos/templates/statefulset-mail.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper-maester/templates/deployment.yaml
- helm/charts/oathkeeper-maester/values.yaml
- helm/charts/oathkeeper/templates/deployment-controller.yaml
- helm/charts/oathkeeper/templates/deployment-sidecar.yaml
- helm/charts/oathkeeper/values.yaml
> feat: expose terminationGracePeriodSeconds

- hacks/values/hydra.yaml
- hacks/values/keto.yaml
- hacks/values/kratos.yaml
- hacks/values/oathkeeper.yaml
- helm/charts/hydra/README.md
- helm/charts/hydra/templates/hpa.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/hpa.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/hpa.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/templates/hpa-controller.yaml
- helm/charts/oathkeeper/values.yaml
> feat: add behavior to hpa spec

- helm/charts/hydra/README.md
- helm/charts/hydra/templates/deployment-watcher.yaml
- helm/charts/hydra/templates/janitor-cron-job-rbac.yaml
- helm/charts/hydra/templates/job-rbac.yaml
- helm/charts/hydra/templates/rbac-watcher.yaml
- helm/charts/hydra/templates/rbac.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/deployment-watcher.yaml
- helm/charts/keto/templates/job-rbac.yaml
- helm/charts/keto/templates/rbac-watcher.yaml
- helm/charts/keto/templates/rbac.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/deployment-watcher.yaml
- helm/charts/kratos/templates/job-rbac.yaml
- helm/charts/kratos/templates/rbac.yaml
- helm/charts/kratos/values.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/templates/rbac.yaml
- helm/charts/oathkeeper/values.yaml
> chore: don't automount sa tokens

- helm/charts/keto/README.md
- helm/charts/keto/templates/job-migration.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/templates/job-migration.yaml
> fix: keto and kratos job resources

- .github/actions/deps-setup/action.yaml
- .github/workflows/ci.yaml
- .github/workflows/closed_references.yaml
- .github/workflows/closed_references.yml
- .github/workflows/conventional_commits.yaml
- .github/workflows/conventional_commits.yml
- .github/workflows/format.yaml
- .github/workflows/labels.yaml
- .github/workflows/labels.yml
- .github/workflows/licenses.yaml
> chore: bump deprecated action

- helm/charts/keto/templates/deployment.yaml
The Keto chart references the Deployment strategy from the wrong location in the values.yaml file, this change updates the Deployment spec to use the correct location.
Fixes #697
> fix: keto Deployment strategy reference

- helm/charts/hydra/templates/janitor-cron-job.yaml
- helm/charts/hydra/values.yaml
This patch allows to specify a custom command for the Janitor CronJob via `values.yaml`
> feat: adding cronjob custom command in hydra

- hacks/values/hydra.yaml
- helm/charts/hydra/README.md
- helm/charts/hydra/templates/janitor-cron-job.yaml
- helm/charts/hydra/values.yaml
Allow mounting volumes to the Janitor. Particularly useful when connecting to the remote DB requires secrets that should be mounted.
> feat: allow extra volumes for janitor

- helm/charts/kratos/Chart.yaml
- helm/charts/kratos/values.yaml
> chore: upgrade Kratos image to v1.3.0

- helm/charts/hydra/README.md
- helm/charts/hydra/templates/deployment.yaml
- helm/charts/hydra/values.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/deployment.yaml
- helm/charts/keto/values.yaml
- helm/charts/kratos/README.md
- helm/charts/kratos/templates/deployment-kratos.yaml
- helm/charts/kratos/values.yaml
- This PR deprecates the default liveness Probes, and updates existing probes to be more in line with with [good practices](https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html)
> chore: deprecate liveness probes

- helm/charts/keto/README.md
- helm/charts/keto/templates/service-read.yaml
- helm/charts/keto/templates/service-write.yaml
- helm/charts/keto/values.yaml
> feat: add headless services to keto

- helm/charts/hydra-maester/Chart.yaml
- helm/charts/hydra-maester/README.md
- helm/charts/hydra-maester/values.yaml
- helm/charts/oathkeeper-maester/Chart.yaml
- helm/charts/oathkeeper-maester/README.md
- helm/charts/oathkeeper-maester/values.yaml
- fixes https://github.com/ory/k8s/issues/723
> fix: do not pint to arch in maester images

- helm/charts/oathkeeper/Chart.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/values.yaml
> chore: bump oathkeeper to 0.40.9

- Makefile
- scripts/setVersions.sh
> fix: rewrite release procedure for new yq

- hacks/helm-validate.sh
- helm/charts/hydra/templates/service-admin.yaml
- helm/charts/keto/README.md
- helm/charts/kratos/templates/service-admin.yaml
- helm/charts/kratos/templates/statefulset-svc.yaml
- helm/charts/oathkeeper/README.md
- helm/charts/oathkeeper/templates/service-metrics.yaml
- helm/charts/oathkeeper/values.yaml
> chore: add capability check for servicemonitor

- .deps/actionlint.yaml
- .github/workflows/ci.yaml
- .github/workflows/gha-lint.yaml
- Makefile
- hacks/helm-test.sh
- hacks/helm-upgrade.sh
- hacks/helm-validate.sh
> chore: upgrade pipeline followups

- helm/charts/hydra-maester/README.md
- helm/charts/hydra-maester/crds/crd-oauth2clients.yaml
- helm/charts/hydra-maester/values.yaml
Related to https://github.com/ory/hydra-maester/releases/tag/v0.0.37
> feat: bump hydra-maester version to 0.0.37

- helm/charts/example-idp/README.md
- helm/charts/hydra/README.md
- helm/charts/hydra/templates/hpa-controller.yaml
- helm/charts/keto/README.md
- helm/charts/keto/templates/hpa-controller.yaml
- helm/charts/kratos/templates/hpa-kratos.yaml
- helm/charts/oathkeeper/templates/hpa.yaml
> fix: hpa using invalid container name
